---
- hosts: 172.17.0.1
  remote_user: videk

  tasks:
  - name: Create directory
    file:
      path: ~/LOG-a-TEC-testbed
      state: directory

# recursive will also download the submodules
# on the version param you can change which branch to pull TODO
  - name: Pull all changes from github
    git:
      repo: git@github.com:logatec3/LOG-a-TEC-testbed.git
      dest: ~/LOG-a-TEC-testbed
      recursive: yes
      update: yes
      force: yes
      depth: 1
      version: master
      
# -f flag so we can later copy whole LOG-a-TEC directory into container
# else we get error "Forbidden path outside the build context"
  - name: Build docker file
    command: docker build -t vesna-drivers -f deploy/docker/Dockerfile .
    args:
      chdir: ~/LOG-a-TEC-testbed

# Save docker image
  - name: Save docker image as a tar file
    command: docker save -o ~/LOG-a-TEC-testbed/Docker-image.tar vesna-drivers

# Copy image to vide-ci container into folder LOG-a-TEC
  - name: Fetch image back to container
    synchronize:
      src: ~/LOG-a-TEC-testbed/Docker-image.tar
      dest: ../../
      mode: pull


# Send image to the targets/nodes
#  - name: Send images to nodes
#    command: scp Docker-image.tar videk@"{{item}}":/home/videk/
#    with_items: 
#      - 192.168.12.81
#      - 192.168.12.83
#      - 192.168.12.87
