---
    - hosts: 172.17.0.1
      remote_user: videk
      tasks:

      - name: cleanup docker container controller
        command: docker stop controller
 
      - name: copy file from container
        command: docker cp controller:/root/LOG-a-TEC-testbed/deploy/tasks/results/ .
        args:
          chdir: ~/experiment
          
      - name: get files from folder
        find:
          paths: "~/experiment/results"
          recurse: no
          patterns: "*.txt"
        register: file

      - name: fetch data file to out
        fetch:
          src: "{{ item.path }}"
          dest: ../../../../out/  #TODO change this directory
          flat: yes
        with_items: "{{ file.files }}"

      - name: delete results
        file: 
          path: ~/experiment/results
          state: absent
    