---
- hosts: 172.17.0.1
  remote_user: videk
  tasks:
  - name: Create directory
    file:
      path: ~/LOG-a-TEC-testbed
      state: directory

# recursive will also download the submodules
# on the version you can change the branch to pull TODO
  - name: Pull all changes from github
    git:
      repo: git@github.com:logatec3/LOG-a-TEC-testbed.git
      dest: ~/LOG-a-TEC-testbed
      recursive: no
      update: yes
      version: master

  - name: Build docker file
    command: docker build -t vesna-drivers .
    args:
      chdir: ~/LOG-a-TEC-testbed/deploy/docker

  - name: Cleanup old docker container (controller)
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill controller
      - docker rm controller

  - name: Run docker image
    command: docker run --privileged --name controller -e TEST=deploy/tasks -e TARGET=server_socket -e NODES_NUM=19 -p 50000:50000 vesna-drivers 
