---
- hosts: 172.17.0.1
  remote_user: videk
  tasks:
  - name: Creates directory
    file:
      path: ~/experiment 
      state: directory

  - name: deploy repo changes
    synchronize:
      src: "{{ lookup('env','PWD') }}"
      dest: ~/experiment
      delete: yes
      recursive: yes

  - name: build docker file
    command: docker build -t vesna-drivers .
    args:
      chdir: ~/experiment/LOG-a-TEC-testbed/deploy/docker

  - name: cleanup docker container controller
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill controller
      - docker rm controller

  - name: run docker image
    command: docker run --privileged --name controller -e TEST=deploy/tasks -e TARGET=server_socket -e NODES_NUM=19 -p 50000:50000 vesna-drivers 
