---
- hosts: 172.17.0.1
  remote_user: videk

# Define number of nodes in use and duration of an application. Used in server.py for timeout so the controller doesn't hang. 
# Just for backup - if all results came from devices, controller will finish its execution. 
  vars:
    nodes: 2
    duration: 5

  - name: Cleanup old docker container (controller)
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill controller
      - docker rm controller

  - name: Run docker image
    command: docker run --privileged --name controller -e TARGET=run_server -e NODES_NUM="{{nodes}}" -e APP_DURATION_MIN="{{duration}}" -p 50000:50000 vesna-drivers 

# We need this otherwise docker will use this one for the next experiment
#  - name: Delete docker .tar file
#    file: 
#      path:  ~/LOG-a-TEC-testbed/Docker-image.tar
#      state: absent
